<?php

return [
    'brand' => [
        'name' => 'SzoftLab',
        'tagline' => 'Kulcsrakész rendszerek, amelyek időt és munkát spórolnak.',
        'contact_email' => env('SZOFTLAB_CONTACT_EMAIL') ?: 'munka@szoftlab.hu',
    ],
    'contact_email' => env('SZOFTLAB_CONTACT_EMAIL') ?: 'munka@szoftlab.hu',
    'privacy_version' => '2026-09-28',
    'inquiry_retention_months' => 12,
    'legal' => [
        'trading_name' => 'SzoftLab',
        'provider_name' => 'Papp Zoltán egyéni vállalkozó',
        'registered_address' => '4937 Barabás, Petőfi Sándor utca 26.',
        'registration_number' => '61241385',
        'registering_authority' => 'Nemzeti Adó- és Vámhivatal',
        'tax_number' => '91482877-1-35',
    ],
    'inquiry_rate_limit' => (int) env('PZDIGITAL_INQUIRY_RATE_LIMIT', 8),
    'featured_project_slug' => 'gyroscity',
    'homepage_story_project_slugs' => ['napiinfo', 'gyroscity', 'zcutzbarber'],
    'home' => [
        'show_references' => (bool) env('PZDIGITAL_HOME_SHOW_REFERENCES', true),
        'enable_product_design_preview' => (bool) env('PZDIGITAL_HOME_ENABLE_PRODUCT_DESIGN_PREVIEW', false),
        'product_placeholder' => [
            'name' => 'Következő saját termék',
            'summary' => 'A részletes bemutató előkészítés alatt.',
        ],
    ],
    'inquiry_interests' => [
        'website' => 'Új céges weboldal',
        'business_system' => 'Egyedi üzleti rendszer',
        'existing_system' => 'Meglévő rendszer továbbfejlesztése',
        'custom_development' => 'Más egyedi fejlesztés',
        'other' => 'Általános egyeztetés',
    ],

    'product_offer' => [
        'price_model' => 'Egyszeri vételár',
        'included_start' => '3 hónap díjmentes tárhely és domain',
        'setup' => 'Segítség a beüzemelésben',
        'note' => 'A 4. hónaptól kedvezményes tárhelydíjjal számolhatsz. A domain további feltételeit és a pontos díjakat az írásos ajánlat rögzíti; igény esetén hosszú távú támogatásról külön egyeztetünk.',
    ],
    'products' => [
        'szervizpro' => [
            'slug' => 'szervizpro',
            'name' => 'SzervizPRO',
            'eyebrow' => 'Szervizeknek tervezett rendszer',
            'headline' => 'Kevesebb adminisztráció. Átláthatóbb szervizmunka.',
            'summary' => 'Digitális munkalap, ügyfélkövetés és műhelykommunikáció egy átlátható rendszerben — kis- és közepes autószervizeknek.',
            'audience' => 'Kis- és közepes szervizek',
            'lifecycle_status' => 'pilot',
            'status_label' => 'Bemutató elérhető',
            'publication_status' => 'published',
            'content_approved' => true,
            'sort_order' => 10,
            'featured_on_home' => true,
            'demo_mode' => 'gallery',
            'demo_url' => 'https://szerviz.pro/',
            'demo_label' => 'Ügyféloldali bemutató',
            'accent' => 'blue',
            'symbol' => '⌁',
            'visual_label' => 'Bemutató elérhető',
            'visual_title' => 'SzervizPRO · napi műhelyközpont',
            'primary_cta' => 'Árajánlatot kérek',
            'benefits' => [
                'Digitális munkalapok és gyors státuszváltás.',
                'Ügyféloldali követés rendszám és azonosító alapján.',
                'Üzenetek, visszahívási kérések és publikus fotók egy helyen.',
            ],
            'value_points' => [
                ['title' => 'Kevesebb kézi admin', 'text' => 'Az autó, a munka, a felhasznált tételek és az állapot egy munkalap köré rendeződik.'],
                ['title' => 'Kevesebb státuszhívás', 'text' => 'Az ügyfél a kapott azonosítóval maga is ellenőrizheti a javítás nyilvános állapotát.'],
                ['title' => 'Átláthatóbb átadás', 'text' => 'A műhely és az ügyfél ugyanarról a javításról kap követhető tájékoztatást.'],
            ],
            'capabilities' => [
                ['title' => 'Munkalap a felvételtől az átadásig', 'text' => 'Ügyfél, jármű, hiba, munkadíj, tételek, jegyzetek és állapotok egy helyen. A csapat gyorsan látja, mi következik.', 'state' => 'available'],
                ['title' => 'Saját arculat programozás nélkül', 'text' => 'Több előre beállított téma közül választhatsz. A műhely logóját, böngészőikonját és márkaszíneit az adminban magad állíthatod be; a publikus és a kezelőfelület is ehhez igazodik.', 'state' => 'available'],
                ['title' => 'Alkatrész-adatbázis és bizonylatimport', 'text' => 'Szöveges beszállítói PDF-ből tételjavaslat készül. Ellenőrzés és javítás után az alkatrészek munkalaphoz rendelhetők; a bizonytalan sorokat nem véglegesíti automatikusan.', 'state' => 'available'],
                ['title' => 'Ügyféloldali státusz, fotó és üzenet', 'text' => 'Az ügyfél rendszám és kapott azonosító alapján nézheti meg a látható állapotot és képeket, üzenhet vagy visszahívást kérhet.', 'state' => 'available'],
                ['title' => 'E-mail értesítések', 'text' => 'A fontos eseményekről sorba állított e-mail értesítés küldhető; a műhely az értesítések állapotát is követheti.', 'state' => 'available'],
                ['title' => 'Számlatervezet és tételes összesítés', 'text' => 'A munkalapból helyi PDF-számlatervezet és ellenőrizhető tételes összesítés készülhet.', 'state' => 'available'],
                ['title' => 'Számlázz.hu és Billingo', 'text' => 'Számlázz.hu XML-előnézet már készül. Éles számlakibocsátás és Billingo kapcsolat a szolgáltatói beállításokkal együtt külön bevezetési feladat.', 'state' => 'planned'],
            ],
            'flow' => [
                ['title' => 'Munkafelvétel', 'text' => 'Az ügyfél, a jármű, a hiba és a vállalt munka egy rendezett munkalapra kerül.'],
                ['title' => 'Műhelymunka', 'text' => 'A csapat a napi munkaközpontból követi az állapotokat, teendőket és ügyfélkéréseket.'],
                ['title' => 'Ügyféltájékoztatás', 'text' => 'Az ügyfél saját kóddal látja a státuszt, az üzeneteket, a várható elkészülést és a publikus fotókat.'],
            ],
            'home_flow' => [
                ['title' => 'Munkafelvétel', 'icon' => 'flow'],
                ['title' => 'Programozás', 'icon' => 'code'],
                ['title' => 'Egyeztetés', 'icon' => 'people'],
                ['title' => 'Átadás', 'icon' => 'shield'],
            ],
            'screenshots' => [
                ['src' => '/media/pzdigital/szervizpro/dashboard.png', 'alt' => 'A SzervizPRO napi műhelyközpontja munkalap- és kommunikációs áttekintéssel', 'label' => 'Műhelynézet', 'title' => 'A napi teendők egy képernyőn', 'group' => 'A műhelyben', 'width' => 1440, 'height' => 1050],
                ['src' => '/media/pzdigital/szervizpro/work-order.jpg', 'alt' => 'Digitális munkalap tesztadatokkal: jármű, ügyfél, állapot és munkaleírás', 'label' => 'Digitális munkalap', 'title' => 'A javítás minden fontos adata egy helyen', 'group' => 'A műhelyben', 'fit' => 'contain', 'width' => 1940, 'height' => 920],
                ['src' => '/media/pzdigital/szervizpro/work-order-parts.jpg', 'alt' => 'Munkalap alkatrészlistája tesztadatokkal: fékbetét, féktárcsa, motorolaj és tömítés, mennyiséggel és árral', 'label' => 'Alkatrészek', 'title' => 'Alkatrészek és összegek a munkalapon', 'group' => 'A műhelyben', 'fit' => 'contain', 'width' => 1550, 'height' => 980],
                ['src' => '/media/pzdigital/szervizpro/customer-home.jpg', 'alt' => 'Teszt Szerviz Kft. ügyféloldali kezdőképernyője állapot-előnézettel, demóadatokkal', 'label' => 'Ügyféloldal', 'title' => 'Kevesebb telefon, érthetőbb tájékoztatás', 'group' => 'Az ügyfélnek', 'fit' => 'contain', 'width' => 1950, 'height' => 790],
                ['src' => '/media/pzdigital/szervizpro/status-lookup.jpg', 'alt' => 'Javítási állapot lekérdezése rendszám és kapott azonosító alapján a Teszt Szerviz Kft. demójában', 'label' => 'Biztonságos lekérdezés', 'title' => 'Rendszám és azonosító alapján', 'group' => 'Az ügyfélnek', 'fit' => 'contain', 'width' => 1950, 'height' => 790],
                ['src' => '/media/pzdigital/szervizpro/customer-status.jpg', 'alt' => 'Ügyféloldali javítási állapot tesztadatokkal: szerelés alatt, várható elkészülés, idővonal és kapcsolatfelvétel', 'label' => 'Javítás követése', 'title' => 'Az ügyfél látja, hol tart az autója', 'group' => 'Az ügyfélnek', 'fit' => 'contain', 'width' => 1950, 'height' => 920],
                ['src' => '/media/pzdigital/szervizpro/print-work-order.jpg', 'alt' => 'Nyomtatásra kész munkalap első része tesztadatokkal: munkalapszám, jármű, állapot és ügyféladatok', 'label' => 'Nyomtatható munkalap', 'title' => 'Papíron is áttekinthető munkalap', 'group' => 'Nyomtatáshoz', 'fit' => 'contain', 'width' => 790, 'height' => 610],
                ['src' => '/media/pzdigital/szervizpro/print-work-order-items.jpg', 'alt' => 'Nyomtatható munkalap tételes alkatrészlistája mennyiséggel, nettó és bruttó árral, tesztadatokkal', 'label' => 'Nyomtatott tételek', 'title' => 'A felhasznált alkatrészek a nyomtatott lapon', 'group' => 'Nyomtatáshoz', 'fit' => 'contain', 'width' => 790, 'height' => 330],
            ],
            'demo_highlights' => [
                ['title' => 'Egy munkalap, a felvételtől az átadásig', 'text' => 'A bemutatón végignézzük a munkafelvételt és az állapotok követését. Így a saját műhelyed egy tipikus feladatán keresztül ismerheted meg a rendszert.', 'image' => null],
                ['title' => 'Az ügyfél is látja, hol tart a javítás', 'text' => 'Megmutatjuk az azonosítós státuszkövetést, az üzeneteket és a megosztható fotókat. Átbeszéljük, mely információkat szeretnéd láthatóvá tenni.', 'image' => null],
            ],
            'related_projects' => [],
            'questions' => [
                ['question' => 'Mit láthatok a bemutatón?', 'answer' => 'A működő műhelynézetet, a digitális munkalapot és az ügyféloldali státuszkövetést mutatjuk meg, a saját folyamataidra koncentrálva.'],
                ['question' => 'A saját szervizem arculatára szabhatom?', 'answer' => 'Igen. Előre beállított témákból indulhatsz, majd a logót, a böngészőikont és a fő márkaszíneket magad módosíthatod az adminban, programozó nélkül.'],
                ['question' => 'Mennyi idő a bevezetés?', 'answer' => 'Az időigényt a szükséges beállítások és adat-előkészítés felmérése után lehet felelősen rögzíteni.'],
                ['question' => 'Működik már az éles számlakibocsátás?', 'answer' => 'Jelenleg számlatervezet és Számlázz.hu XML-előnézet érhető el. Az éles Számlázz.hu és Billingo kapcsolat külön integrációs és szolgáltatói ellenőrzést igényel.'],
                ['question' => 'Bármilyen beszállítói PDF automatikusan importálható?', 'answer' => 'A szöveges PDF-ek felismert sorai ellenőrizhetők és javíthatók. A szkennelt dokumentumok OCR-feldolgozása és minden beszállítói formátum automatikus felismerése jelenleg nem része a rendszernek.'],
            ],
        ],
        'foodpro' => [
            'slug' => 'foodpro',
            'name' => 'FoodPro',
            'eyebrow' => 'Online rendelési megoldás',
            'headline' => 'Saját rendelési felület az éttermednek.',
            'summary' => 'Saját, mobilbarát rendelési felület és kezelőoldal éttermeknek. A visszatérő vendég mentett kedvenceiből gyorsan rendelhet; a csapat egy helyen fogadja, nyomtatja és követi a rendeléseket.',
            'audience' => 'Éttermek és vendéglátóhelyek',
            'lifecycle_status' => 'pilot',
            'status_label' => 'Élő bemutató',
            'publication_status' => 'published',
            'content_approved' => true,
            'sort_order' => 20,
            'featured_on_home' => true,
            'demo_mode' => 'gallery',
            'demo_url' => 'https://foodpro.shop/',
            'demo_label' => 'Élő éttermi bemutató',
            'accent' => 'green',
            'symbol' => '✦',
            'visual_label' => 'FoodPro élő bemutató',
            'visual_title' => 'FoodPro főoldal és gyors rendelés',
            'value_heading' => 'Gyorsabb rendelés, rendezettebb konyhai munka',
            'value_intro' => 'A vendég a saját telefonján választ; az étterem egy kezelőoldalon követi, mit kell elkészíteni.',
            'flow_intro' => 'A vendég rendelési útja és az étterem napi feladatai ugyanabban a rendszerben kapcsolódnak össze.',
            'capabilities_intro' => 'A bemutatóban működő funkciókat és a szerződéshez vagy egyedi beállításhoz kötött részeket külön jelöljük.',
            'demo_intro' => 'Megmutatjuk a rendelést a vendég szemével, majd a beérkező tételeket, a nyomtatást és az étlapkezelést az adminban.',
            'gallery_intro' => 'A képernyőképek a foodpro.shop bemutató példányából, tesztadatokkal készültek. A rendeléskövetési és nyomtatási képen a kapcsolati adatokat bemutató adatokra cseréltük. Az arculatot és a beállításokat az éttermedhez igazíthatod.',
            'primary_cta' => 'Árajánlatot kérek',
            'benefits' => [
                'Gyors rendelési út mobilon és asztali gépen.',
                'Beérkező rendelések kezelése és azonnali nyomtatása.',
                'Mentett kedvencek és címek a visszatérő vendégeknek.',
            ],
            'value_points' => [
                ['title' => 'Gyorsabb újrarendelés', 'text' => 'A vendég a profiljába mentheti kedvenc ételeit és címeit. Visszatérve kevesebb adatot kell újra megadnia.'],
                ['title' => 'Minden rendelés egy helyen', 'text' => 'A beérkező tételeket és rendelési állapotokat a kezelőoldalon látod; a konyhának nyomtatható rendelés készül.'],
                ['title' => 'A saját éttermed arculata', 'text' => 'Előre beállított témákból indulhatsz, majd a logót, a színeket és a fontos tartalmakat saját kezűleg módosíthatod az adminban.'],
            ],
            'capabilities' => [
                ['title' => 'Mobilbarát étlap és gyors rendelés', 'text' => 'Kategóriák, kereshető kínálat, kosár és külön Gyors rendelés gomb segíti a vendéget.', 'state' => 'available'],
                ['title' => 'Mentett kedvencek és címek', 'text' => 'A regisztrált vendég elmentheti kedvenc ételeit és szállítási címeit. A következő rendelésnél a korábban megadott adatokkal néhány lépésben végezhet.', 'state' => 'available'],
                ['title' => 'Termékopciók és extrák', 'text' => 'Az ételnél kiválaszthatók a szószok, elhagyható összetevők, extrák és egyedi kérések.', 'state' => 'available'],
                ['title' => 'Rendeléskezelés és nyomtatás', 'text' => 'A kezelőoldalon megjelennek a rendelési tételek és állapotok; a rendelés nyomtatható konyhai nézetben is elérhető.', 'state' => 'available'],
                ['title' => 'Rendelések követése', 'text' => 'A bejelentkezett vendég a saját rendelései között láthatja az aktuális állapotot és a rendelés részleteit. Az étterem a kezelőoldalon követi és frissíti a folyamatot.', 'state' => 'available'],
                ['title' => 'Étlap és felhasználók kezelése', 'text' => 'Adminból kezelhetők a termékek, kategóriák, árak, képek és felhasználói fiókok.', 'state' => 'available'],
                ['title' => 'Saját arculat programozás nélkül', 'text' => 'Több előre beállított megjelenésből választhatsz. Az adminban magad módosíthatod a logót, a színeket, a képeket és a navigáció fontos elemeit.', 'state' => 'available'],
                ['title' => 'E-mail értesítési sablonok', 'text' => 'A rendszerben fiókellenőrzési, rendelési és állapotértesítési e-mail folyamatok vannak. A kiküldést az adott étterem levelezésével kell beállítani és tesztelni.', 'state' => 'available'],
                ['title' => 'Hírlevél-feliratkozás', 'text' => 'A vendég az oldalon e-mail címmel feliratkozhat, a feliratkozók listája az adminban látható. Kampányküldést külön igényként egyeztetünk.', 'state' => 'available'],
                ['title' => 'Barion, Apple Pay és Google Pay', 'text' => 'A demóban Barion tesztfizetés állítható be. Éles online fizetéshez saját Barion-szerződés, kereskedői beállítás és beüzemelési teszt kell. Az Apple Pay és a Google Pay az adott kereskedőnél és vendégeszközön támogatott fizetési módokkal érhető el.', 'state' => 'planned'],
            ],
            'flow' => [
                ['title' => 'Választás', 'text' => 'A vendég mobilon vagy gépen böngészi az étlapot, és összeállítja a választott ételt.'],
                ['title' => 'Rendelés', 'text' => 'A kosárból vagy mentett kedvencéből indul, és a profiljában megőrzött címet is felhasználhatja.'],
                ['title' => 'Elkészítés és követés', 'text' => 'A csapat fogadja és kinyomtatja a rendelést, a vendég pedig a saját fiókjában látja annak állapotát.'],
            ],
            'screenshots' => [
                ['src' => '/media/pzdigital/foodpro/home-desktop.png', 'alt' => 'A FoodPro bemutató étterem főoldala étlap gombbal és kategóriakártyákkal', 'label' => 'Vendégoldali főoldal', 'title' => 'Innen indul a rendelés', 'group' => 'A vendégnek', 'width' => 1440, 'height' => 1050],
                ['src' => '/media/pzdigital/foodpro/menu.png', 'alt' => 'FoodPro bemutató étlapja termékkártyákkal és árakkal', 'label' => 'Vendégoldali étlap', 'title' => 'A kínálat gyorsan áttekinthető', 'group' => 'A vendégnek', 'width' => 1350, 'height' => 530],
                ['src' => '/media/pzdigital/foodpro/product-options.png', 'alt' => 'FoodPro termékoldal választható szószokkal és elhagyható összetevőkkel', 'label' => 'Termékopciók', 'title' => 'Személyre szabható étel', 'group' => 'A vendégnek', 'width' => 1360, 'height' => 890],
                ['src' => '/media/pzdigital/foodpro/quick-order.png', 'alt' => 'FoodPro termékoldal extrákkal, speciális kérés mezővel és Gyors rendelés gombbal', 'label' => 'Gyors rendelés', 'title' => 'Rövid út a rendelésig', 'group' => 'A vendégnek', 'width' => 2560, 'height' => 1249],
                ['src' => '/media/pzdigital/foodpro/checkout.png', 'alt' => 'FoodPro pénztár üres vendégadat mezőkkel, kiszállítási és fizetési választással, rendelési összegzéssel', 'label' => 'Pénztár', 'title' => 'Átlátható megrendelés és összegzés', 'group' => 'A vendégnek', 'width' => 2545, 'height' => 1242],
                ['src' => '/media/pzdigital/foodpro/mobile-home.png', 'alt' => 'FoodPro bemutató kezdőlapja mobiltelefon méretben', 'label' => 'Mobilos kezdőlap', 'title' => 'Telefonon is kényelmes indulás', 'group' => 'A vendégnek', 'orientation' => 'portrait', 'width' => 390, 'height' => 844],
                ['src' => '/media/pzdigital/foodpro/mobile-menu.png', 'alt' => 'FoodPro mobilos étlapja termékekkel és alsó navigációval', 'label' => 'Mobilos étlap', 'title' => 'Gyors választás kis képernyőn', 'group' => 'A vendégnek', 'orientation' => 'portrait', 'width' => 390, 'height' => 844],
                ['src' => '/media/pzdigital/foodpro/orders-admin.png', 'alt' => 'FoodPro admin rendeléslista kizárólag bemutató rendeléssel és állapotjelzésekkel', 'label' => 'Rendelések', 'title' => 'Beérkezett rendelések egy helyen', 'group' => 'Az étteremnek', 'width' => 2560, 'height' => 1249],
                ['src' => '/media/pzdigital/foodpro/catalog-admin.png', 'alt' => 'FoodPro admin termékfelvételi űrlap kategóriával, árral, extrákkal és képpel', 'label' => 'Étlapkezelés', 'title' => 'Termékek és opciók az adminban', 'group' => 'Az étteremnek', 'width' => 2545, 'height' => 1242],
                ['src' => '/media/pzdigital/foodpro/users-admin.png', 'alt' => 'FoodPro admin új felhasználó felvételi űrlapja üres mezőkkel', 'label' => 'Felhasználók', 'title' => 'Felhasználói fiókok kezelése', 'group' => 'Az étteremnek', 'width' => 2560, 'height' => 1249],
                ['src' => '/media/pzdigital/foodpro/order-tracking.png', 'alt' => 'FoodPro vendégoldali rendelésrészlet tesztadatokkal: aktuális Átvehető állapot, tételek, fizetés és végösszeg', 'label' => 'Vendégoldali követés', 'title' => 'A vendég látja a rendelés állapotát', 'group' => 'Rendelés követése', 'width' => 1310, 'height' => 795],
                ['src' => '/media/pzdigital/foodpro/print-receipt.png', 'alt' => 'FoodPro 80 milliméteres nyomtatási nézet demó rendeléssel: tételek, extrák, díjak és végösszeg', 'label' => 'Nyomtatható rendelés', 'title' => 'A konyha azonnal megkapja a tételeket', 'group' => 'Nyomtatáshoz', 'fit' => 'contain', 'orientation' => 'portrait', 'width' => 292, 'height' => 555],
                ['src' => '/media/pzdigital/foodpro/barion-admin.png', 'alt' => 'FoodPro fizetési módok: készpénz, kártya átvételkor és Barion tesztbeállítás éles fizetés nélkül', 'label' => 'Fizetési módok', 'title' => 'Online fizetés Barion-kapcsolattal', 'group' => 'Integrációk', 'width' => 1580, 'height' => 850],
            ],
            'demo_highlights' => [
                ['title' => 'A vendég néhány lépésben rendel', 'text' => 'Megmutatjuk a mobilos étlapot, a választható extrákat, a mentett kedvenceket és a gyors rendelési utat.', 'image' => null],
                ['title' => 'A csapat azonnal látja a rendelést', 'text' => 'Végigvesszük a kezelőoldali rendeléslistát, a nyomtatható rendelési nézetet és az étlap napi szerkesztését.', 'image' => null],
            ],
            'related_projects' => [],
            'questions' => [
                ['question' => 'Megnézhetem működés közben?', 'answer' => 'Igen, a foodpro.shop oldalon bemutató étterem és mintatartalom látható. A saját éttermedhez szükséges beállításokat ajánlat alapján készítjük el.'],
                ['question' => 'A vendégek elmenthetik kedvenceiket és címüket?', 'answer' => 'Igen. Regisztrált fiókban elmenthetik kedvenc ételeiket és a szállítási címeket, így a következő rendeléshez kevesebb adatot kell újra megadniuk.'],
                ['question' => 'Magam is alakíthatom az oldal kinézetét?', 'answer' => 'Igen. Az előre beállított témák mellett az adminban szerkeszthetők a logók, a márkaszínek, a képek és több navigációs elem. Ezekhez nincs szükség programozóra.'],
                ['question' => 'Van Apple Pay és Google Pay?', 'answer' => 'A Barion Smart Gateway támogatja ezeket a fizetési módokat. Megjelenésük a kereskedői szerződéstől, a Barion engedélyezésétől és a vendég eszközétől függ. A FoodPro demó jelenleg tesztmódban működik; az éles fizetést külön üzemeljük be.'],
                ['question' => 'Hogyan működnek az e-mail értesítések?', 'answer' => 'Fiókellenőrzési, rendelési és állapotértesítési e-mail folyamatok állnak rendelkezésre. Az éles kiküldést az étterem saját levelezésével kell beállítani és ellenőrizni.'],
                ['question' => 'Mit kapok az egyszeri vételárért?', 'answer' => 'A pontos funkciókat és beüzemelési feladatokat az ajánlat rögzíti. Az induláshoz 3 hónap díjmentes tárhely és domain tartozik; a 4. hónaptól kedvezményes tárhelydíjjal számolhatsz. A domain további feltételeit az ajánlat tartalmazza. Igény esetén hosszú távú támogatásról külön egyeztetünk.'],
            ],
        ],
    ],

    'projects' => [
        'gyroscity' => [
            'slug' => 'gyroscity',
            'name' => 'GyrosCity',
            'showcase_headline' => 'GyrosCity — saját étlap és rendelési felület',
            'showcase_label' => 'Rendelés',
            'showcase_title' => 'Rendelési felület és kezelőoldali feldolgozás',
            'showcase_flow' => 'Étlap → rendelés → adminisztrátori kezelés',
            'home_feature' => 'Online rendelés és rendeléskezelő admin',
            'summary' => 'Éttermi weboldal és online rendelési felület kategóriákkal, kínálati kártyákkal és kosárfolyamattal.',
            'purpose' => 'A vendégek közvetlenül az étterem saját oldalán választhatnak ételt és adhatnak le rendelést; a csapat a beérkező rendeléseket egy kezelőfelületen dolgozhatja fel.',
            'categories' => ['Éttermi weboldal', 'Online rendelés'],
            'project_type' => 'client_project',
            'delivery_context' => 'founder_prior_work',
            'role_description' => 'Korábbi fejlesztői munka a SzoftLab mögötti szakmai tapasztalatból.',
            'year' => null,
            'publication_status' => 'published',
            'content_approved' => true,
            'featured_on_home' => true,
            'sort_order' => 10,
            'public_url' => 'https://gyroscity.eu/',
            'accent' => 'amber',
            'media' => [
                ['src' => '/media/pzdigital/references/gyroscity/menu-desktop.jpg', 'card_src' => '/media/pzdigital/references/gyroscity/menu-card.jpg', 'alt' => 'GyrosCity online étlap több valódi termékkártyával, nevekkel és árakkal', 'viewport' => '1440 × 1000'],
                ['src' => '/media/pzdigital/references/gyroscity/menu-mobile.jpg', 'alt' => 'GyrosCity mobilos étlapja a népszerű termékek listájával', 'viewport' => '390 × 844'],
            ],
            'case_study_sections' => [
                'task' => 'Egy éttermi kínálat és a rendelési út áttekinthető megjelenítése asztali és mobilfelületen.',
                'role' => 'A publikus webes felület és a rendelési folyamat fejlesztése korábbi szakmai projektként.',
                'solutions' => ['Kategóriákba rendezett étlap', 'Termékkártyák és kosárfelület', 'Mobilra alkalmazkodó vásárlói nézet'],
            ],
            'case_study' => [
                'headline' => 'GyrosCity — étlap és rendeléskezelés egy rendszerben.',
                'lead' => 'Az éttermi kínálat böngészésétől a rendelés kezelőoldali feldolgozásáig egy összefüggő webes folyamat készült.',
                'audience' => 'Éttermi vendégek és a rendeléseket kezelő csapat',
                'blocks' => [
                    ['type' => 'overview', 'heading' => 'A vendégoldal és a háttérfolyamat', 'public_side' => 'A vendég kategóriák szerint böngészi a kínálatot, terméket választ, majd a rendelési úton halad tovább.', 'admin_side' => 'A beérkező rendelések az adminfelületen kezelhetők.', 'publication_status' => 'published', 'evidence_status' => 'owner_confirmed'],
                    ['type' => 'workflow', 'heading' => 'Hogyan működik?', 'steps' => [
                        ['title' => 'Étlap', 'body' => 'A valós terméklistán kategóriák, terméknevek és árak jelennek meg.'],
                        ['title' => 'Rendelés', 'body' => 'A kiválasztott tételek a vendégoldali rendelési folyamatba kerülnek.'],
                        ['title' => 'Feldolgozás', 'body' => 'A rendelést a kezelőoldali adminisztrációban lehet feldolgozni.'],
                    ], 'publication_status' => 'published', 'evidence_status' => 'owner_confirmed'],
                    ['type' => 'integration', 'heading' => 'Vendégoldal és kezelőoldal egy projektben', 'body' => 'A GyrosCity saját étlapja és rendeléskezelő adminja külön megbízás keretében készült. Az itt látható működés a projekt saját megoldása.', 'publication_status' => 'published', 'evidence_status' => 'owner_confirmed'],
                    ['type' => 'gallery', 'heading' => 'A valódi étlapfelület', 'body' => 'Nyilvános asztali és mobilképek; a háttérfolyamatot külön, jelölt szemléltető magyarázza.', 'publication_status' => 'published', 'evidence_status' => 'public_screen'],
                    ['type' => 'outcome', 'heading' => 'Amit megvalósítottunk', 'items' => ['Kategóriákba rendezett, reszponzív étlap', 'Vendégoldali rendelési út', 'Rendeléskezelő adminisztráció'], 'publication_status' => 'published', 'evidence_status' => 'owner_confirmed'],
                ],
                'missing_assets' => ['Jóváhagyott, szintetikus adatú admin-képernyő'],
            ],
            'source_reference' => 'https://pzoli.com/ és https://gyroscity.eu/',
        ],
        'zcutzbarber' => [
            'slug' => 'zcutzbarber',
            'name' => 'ZCutzBarber',
            'showcase_label' => 'Foglalás',
            'showcase_title' => 'Online időpontfoglalás naptárkapcsolattal',
            'showcase_flow' => 'Időpontválasztás → foglalás → Google Naptár-kapcsolat',
            'home_feature' => 'Időpontfoglalás Google Naptár-kapcsolattal',
            'summary' => 'Márkázott szolgáltatói weboldal bemutatkozással, szolgáltatásokkal, árlistával és időpontfoglalási felülettel.',
            'purpose' => 'Az érdeklődő egy helyen találja a szolgáltatásokat, árakat és foglalási lehetőséget; a szolgáltató a foglalásokat naptárkapcsolattal követheti.',
            'categories' => ['Szolgáltatói weboldal', 'Időpontfoglalás'],
            'project_type' => 'client_project',
            'delivery_context' => 'founder_prior_work',
            'role_description' => 'Korábbi fejlesztői munka a SzoftLab mögötti szakmai tapasztalatból.',
            'year' => null,
            'publication_status' => 'published',
            'content_approved' => true,
            'featured_on_home' => true,
            'sort_order' => 20,
            'public_url' => 'https://zcutzbarber.com/',
            'accent' => 'lime',
            'media' => [
                ['src' => '/media/pzdigital/references/zcutzbarber/desktop.jpg', 'alt' => 'ZCutzBarber szolgáltatói weboldal — asztali képernyőkép', 'viewport' => '1440 × 1000'],
                ['src' => '/media/pzdigital/references/zcutzbarber/mobile.jpg', 'alt' => 'ZCutzBarber mobilos bemutatkozó felület — képernyőkép', 'viewport' => '390 × 844'],
            ],
            'case_study_sections' => [
                'task' => 'A barber márka, a szolgáltatások és a kapcsolatfelvételi lehetőségek egységes online bemutatása.',
                'role' => 'A publikus márkaoldal és a látogatói út fejlesztése korábbi szakmai projektként.',
                'solutions' => ['Márkázott bemutatkozó felület', 'Szolgáltatás- és árlista', 'Látható időpontfoglalási lehetőség'],
            ],
            'case_study' => [
                'headline' => 'ZCutzBarber — online foglalás, naptárkapcsolattal.',
                'lead' => 'A márkaoldal az időpontfoglalási utat Google Naptár-kapcsolattal egészíti ki.',
                'audience' => 'Vendégek és a foglalásokat kezelő szolgáltató',
                'blocks' => [
                    ['type' => 'overview', 'heading' => 'Szolgáltatási oldal és foglalási háttér', 'public_side' => 'A látogató megismeri a szolgáltatásokat és az árakat, majd eléri az online időpontfoglalást.', 'admin_side' => 'A foglalás kezelése Google Naptár-kapcsolathoz illeszkedik. A szinkron irányáról, idejéről vagy ütközéskezeléséről nincs publikált állítás.', 'publication_status' => 'published', 'evidence_status' => 'owner_confirmed'],
                    ['type' => 'workflow', 'heading' => 'Hogyan működik?', 'steps' => [
                        ['title' => 'Időpontválasztás', 'body' => 'A vendég a foglalási felületen választ megfelelő időpontot.'],
                        ['title' => 'Foglalás kezelése', 'body' => 'A kiválasztás kezelhető foglalássá válik a szolgáltatói folyamatban.'],
                        ['title' => 'Naptárkapcsolat', 'body' => 'A rendszer kapcsolódik a Google Naptárhoz; a szemléltetés nem hoz létre valódi eseményt.'],
                    ], 'publication_status' => 'published', 'evidence_status' => 'owner_confirmed'],
                    ['type' => 'integration', 'heading' => 'Google Naptár-kapcsolat, pontos határokkal', 'body' => 'A naptárkapcsolat megerősített funkció. Kétirányú szinkront, automatikus emlékeztetőt, fizetést vagy garantált ütközésmentességet nem állítunk.', 'publication_status' => 'published', 'evidence_status' => 'owner_confirmed'],
                    ['type' => 'gallery', 'heading' => 'Márka- és foglalási felület', 'body' => 'A nyilvános képek a szolgáltatói weboldalt mutatják; naptárképernyő csak jóváhagyott tesztadatból kerülhet ki később.', 'publication_status' => 'published', 'evidence_status' => 'public_screen'],
                    ['type' => 'outcome', 'heading' => 'Igazoltan elkészült', 'items' => ['Márkázott szolgáltatói weboldal', 'Online időpontfoglalás', 'Google Naptár-kapcsolat'], 'publication_status' => 'published', 'evidence_status' => 'owner_confirmed'],
                ],
                'missing_assets' => ['Jóváhagyott, tesztadatú naptárképernyő'],
            ],
            'source_reference' => 'https://pzoli.com/ és https://zcutzbarber.com/',
        ],
        'tiszaszalka-se' => [
            'slug' => 'tiszaszalka-se',
            'name' => 'Tiszaszalka SE',
            'showcase_label' => 'Adatszinkron',
            'showcase_title' => 'Sporteredmények automatikus átvétele',
            'showcase_flow' => 'MLSZ Adatbank → automatikus átvétel → kluboldal',
            'summary' => 'Sportegyesületi weboldal hírekkel, mérkőzésadatokkal, tabellával, dokumentumokkal és galériával.',
            'purpose' => 'A szurkolók és játékosok megtalálják a klub híreit és eredményeit; az automatikus MLSZ-adatátvétel csökkenti a kézi eredményrögzítést.',
            'categories' => ['Egyesületi weboldal', 'Sporttartalom'],
            'project_type' => 'client_project',
            'delivery_context' => 'founder_prior_work',
            'role_description' => 'Korábbi fejlesztői munka a SzoftLab mögötti szakmai tapasztalatból.',
            'year' => null,
            'publication_status' => 'published',
            'content_approved' => true,
            'featured_on_home' => false,
            'sort_order' => 30,
            'public_url' => 'https://tiszaszalkase.com/',
            'accent' => 'forest',
            'media' => [
                ['src' => '/media/pzdigital/references/tiszaszalka-se/desktop.jpg', 'alt' => 'Tiszaszalka SE sportegyesületi weboldal — asztali képernyőkép', 'viewport' => '1440 × 1000'],
                ['src' => '/media/pzdigital/references/tiszaszalka-se/mobile.jpg', 'alt' => 'Tiszaszalka SE mobilos weboldal — képernyőkép', 'viewport' => '390 × 844'],
            ],
            'case_study_sections' => [
                'task' => 'Az egyesületi hírek és a nyilvános sportinformációk rendezett, közös felületen történő bemutatása.',
                'role' => 'A publikus információs oldal fejlesztése korábbi szakmai projektként.',
                'solutions' => ['Hírek és mérkőzéslista', 'Tabella és szezoninformációk', 'Dokumentumok és képgaléria'],
            ],
            'case_study' => [
                'headline' => 'Tiszaszalka SE — eredmények, kézi másolgatás nélkül.',
                'lead' => 'A sportoldal az MLSZ Adatbankból automatikusan átvett eredményeket rendezi a klub saját felületére.',
                'audience' => 'Szurkolók, játékosok és az egyesületi tartalmak kezelői',
                'blocks' => [
                    ['type' => 'overview', 'heading' => 'Kluboldal és adatforrás', 'public_side' => 'A látogató híreket, mérkőzésadatokat, eredményeket és a klub további nyilvános tartalmait éri el.', 'admin_side' => 'Az eredmények forrása az MLSZ Adatbank, ahonnan automatikus átvétel történik. A bemutató nem állít valós idejű vagy kétirányú kapcsolatot.', 'publication_status' => 'published', 'evidence_status' => 'owner_confirmed'],
                    ['type' => 'workflow', 'heading' => 'Hogyan működik?', 'steps' => [
                        ['title' => 'Forrásadat', 'body' => 'A mérkőzés eredménye az MLSZ Adatbank nyilvános sportadatából indul.'],
                        ['title' => 'Automatikus átvétel', 'body' => 'A rendszer a szükséges eredményadatot automatikusan átveszi.'],
                        ['title' => 'Kluboldali megjelenés', 'body' => 'Az adat a Tiszaszalka SE saját eredményfelületén jelenik meg.'],
                    ], 'publication_status' => 'published', 'evidence_status' => 'owner_confirmed'],
                    ['type' => 'integration', 'heading' => 'MLSZ Adatbank, nem banki adatforrás', 'body' => 'A forrás megnevezése MLSZ Adatbank. Nincs állítás hivatalos API-partnerségről, élő frissítési garanciáról vagy kétirányú adatszinkronról.', 'publication_status' => 'published', 'evidence_status' => 'owner_confirmed'],
                    ['type' => 'gallery', 'heading' => 'A klub nyilvános felülete', 'body' => 'A képek az egyesület asztali és mobiloldalát mutatják; a forrástól a felületig tartó út jelölt szemléltetés.', 'publication_status' => 'published', 'evidence_status' => 'public_screen'],
                    ['type' => 'outcome', 'heading' => 'Igazoltan elkészült', 'items' => ['Egyesületi hírek és mérkőzésadatok', 'Automatikus eredményátvétel az MLSZ Adatbankból', 'Reszponzív kluboldali megjelenés'], 'publication_status' => 'published', 'evidence_status' => 'owner_confirmed'],
                ],
                'missing_assets' => ['Publikálható forrásimport-napló vagy admin-képernyő'],
            ],
            'source_reference' => 'https://pzoli.com/ és https://tiszaszalkase.com/',
        ],
        'napiinfo' => [
            'slug' => 'napiinfo',
            'name' => 'NapiInfo',
            'showcase_label' => 'AI-tartalom',
            'showcase_title' => 'Tulajdonosi utasításból szerkeszthető cikk',
            'showcase_flow' => 'Utasítás → AI-cikktervezet → szerkesztési folyamat',
            'home_feature' => 'AI-val támogatott cikkgyártás',
            'summary' => 'Tartalmi portál kiemelt cikkekkel, témakörökkel, friss hírekkel és többféle olvasási belépési ponttal.',
            'purpose' => 'Az olvasók témák szerint fedezhetik fel a cikkeket; a szerkesztők a tulajdonosi iránymutatásból induló cikktervezeteket dolgozhatják fel.',
            'categories' => ['Tartalmi portál', 'Szerkesztett cikkek'],
            'project_type' => 'unspecified',
            'delivery_context' => 'founder_prior_work',
            'role_description' => 'Korábbi fejlesztői munka a SzoftLab mögötti szakmai tapasztalatból.',
            'year' => null,
            'publication_status' => 'published',
            'content_approved' => true,
            'featured_on_home' => true,
            'sort_order' => 40,
            'public_url' => 'https://napiinfo.com/',
            'accent' => 'red',
            'media' => [
                ['src' => '/media/pzdigital/references/napiinfo/desktop.jpg', 'alt' => 'NapiInfo tartalmi portál — asztali képernyőkép', 'viewport' => '1440 × 1000'],
                ['src' => '/media/pzdigital/references/napiinfo/mobile.jpg', 'alt' => 'NapiInfo mobilos cikkfelület — képernyőkép', 'viewport' => '390 × 844'],
            ],
            'case_study_sections' => [
                'task' => 'Sokféle témájú cikk áttekinthető szervezése és több belépési pont biztosítása az olvasóknak.',
                'role' => 'A publikus tartalmi felület fejlesztése korábbi szakmai projektként.',
                'solutions' => ['Kiemelt és friss cikkek', 'Témakörök és kategóriaoldalak', 'Reszponzív tartalmi kártyarendszer'],
            ],
            'case_study' => [
                'headline' => 'NapiInfo — az utasítástól a cikkig.',
                'lead' => 'AI-val támogatott tartalom-előállítás, amely a tulajdonosi iránymutatást kapcsolja össze a weboldal szerkesztési folyamatával.',
                'audience' => 'A portál tulajdonosa, szerkesztői és olvasói',
                'blocks' => [
                    ['type' => 'overview', 'heading' => 'Olvasói felület és tartalom-előállítás', 'public_side' => 'Az olvasó témakörök, kiemelt és friss cikkek között böngészhet a reszponzív portálon.', 'admin_side' => 'A tulajdonosi utasításból AI-cikktervezet indul, amely szerkesztési folyamatba kerül. A bemutató nem állít felügyelet nélküli automatikus publikálást.', 'publication_status' => 'published', 'evidence_status' => 'owner_confirmed'],
                    ['type' => 'workflow', 'heading' => 'Hogyan működik?', 'steps' => [
                        ['title' => 'Tulajdonosi utasítás', 'body' => 'A folyamat egy előre megadott témából és iránymutatásból indul.'],
                        ['title' => 'AI-cikktervezet', 'body' => 'A rendszer szerkeszthető cikktervezetet állít össze; ez nem élő AI-futtatás ezen az oldalon.'],
                        ['title' => 'Szerkesztési folyamat', 'body' => 'A tervezet a weboldal tartalomkezelési folyamatába kerül. A publikálás mai pontos rendje külön ellenőrzendő.'],
                    ], 'publication_status' => 'published', 'evidence_status' => 'owner_confirmed_with_historical_boundary'],
                    ['type' => 'integration', 'heading' => 'AI-támogatás, emberi iránymutatással', 'body' => 'A szemléltető helyi, rögzített mintával dolgozik. Nem hív AI-szolgáltatót, nem tartalmaz belső promptot, és nem ígér automatikus tényellenőrzést vagy hibamentességet.', 'publication_status' => 'published', 'evidence_status' => 'owner_confirmed'],
                    ['type' => 'gallery', 'heading' => 'A tényleges portálfelület', 'body' => 'A képek a nyilvános olvasói oldalt mutatják; jóváhagyott, anonimizált szerkesztői kép még nem áll rendelkezésre.', 'publication_status' => 'published', 'evidence_status' => 'public_screen'],
                    ['type' => 'outcome', 'heading' => 'Igazoltan elkészült', 'items' => ['Tulajdonosi iránymutatásból induló AI-cikktervezet', 'Szerkesztési folyamatba kapcsolt tartalom-előállítás', 'Reszponzív, témakörökre rendezett cikkportál'], 'publication_status' => 'published', 'evidence_status' => 'owner_confirmed'],
                ],
                'missing_assets' => ['Jóváhagyott, anonimizált szerkesztői képernyő', 'A jelenlegi publikálási sorrend friss auditja'],
            ],
            'source_reference' => 'https://pzoli.com/ és https://napiinfo.com/',
        ],
        'fotoklikk' => [
            'slug' => 'fotoklikk',
            'name' => 'FotoKlikk',
            'showcase_label' => 'Fotós közösség',
            'showcase_title' => 'Fotósok és tartalmaik egy közösségi felületen',
            'showcase_flow' => 'Alkotók → profilok → képek és események',
            'summary' => 'Fotós közösségi oldal alkotói profilokkal, szervezetekkel, galériákkal, hírekkel és eseményekkel.',
            'purpose' => 'A fotósok és szervezetek bemutathatják munkáikat; a látogatók alkotókat, képeket, eseményeket és fotós tartalmakat fedezhetnek fel.',
            'categories' => ['Közösségi platform', 'Fotózás'],
            'project_type' => 'collaboration',
            'delivery_context' => 'ongoing_collaboration',
            'role_description' => 'Fejlesztői közreműködés a nyilvános felület és kapcsolódó webes folyamatok fejlesztésében.',
            'year' => null,
            'publication_status' => 'published',
            'content_approved' => true,
            'featured_on_home' => false,
            'sort_order' => 50,
            'public_url' => 'https://fotoklikk.net/',
            'accent' => 'blue',
            'media' => [
                ['src' => '/media/pzdigital/references/fotoklikk/desktop.png', 'alt' => 'FotoKlikk alkotói profilok listája szűrési lehetőségekkel', 'viewport' => '1440 × 1000'],
            ],
            'case_study_sections' => [
                'task' => 'Fotós alkotók és közösségi tartalmak áttekinthető nyilvános megjelenítése.',
                'role' => 'Fejlesztői közreműködés a platform nyilvános felületén és egyes kapcsolódó folyamatain.',
                'solutions' => ['Kereshető alkotói profilok', 'Fotós tartalmak és galériák', 'Események és szervezeti oldalak'],
            ],
            'case_study' => [
                'headline' => 'FotoKlikk — a fotós közösség helye',
                'lead' => 'A platformon a fotós alkotók, szervezetek, képek és események közös, böngészhető felületen jelennek meg.',
                'audience' => 'Fotósok, szervezetek és a fotózás iránt érdeklődők',
                'blocks' => [
                    ['type' => 'overview', 'heading' => 'Alkotók és érdeklődők találkozása', 'public_side' => 'A látogatók alkotói profilokat kereshetnek, valamint fotós tartalmakat és eseményeket böngészhetnek.', 'admin_side' => 'A profilok, képek és események rendezett megjelenítése segíti, hogy a közösség tartalmai könnyen felfedezhetők legyenek.', 'publication_status' => 'published', 'evidence_status' => 'public_screen'],
                    ['type' => 'gallery', 'heading' => 'A nyilvános alkotói felület', 'body' => 'A képernyőkép a FotoKlikk nyilvános alkotói keresőjét és profilkártyáit mutatja.', 'publication_status' => 'published', 'evidence_status' => 'public_screen'],
                    ['type' => 'outcome', 'heading' => 'Mit használhat a látogató?', 'items' => ['Kereshető alkotói profilok', 'Fotós hírek és galériák', 'Események és szervezeti tartalmak'], 'publication_status' => 'published', 'evidence_status' => 'public_screen'],
                ],
            ],
            'source_reference' => 'https://fotoklikk.net/',
        ],
    ],
];
