<?php

return [
    'contact_email' => env('PZDIGITAL_CONTACT_EMAIL', 'hello@pzdigital.hu'),
    'privacy_version' => env('PZDIGITAL_PRIVACY_VERSION', 'draft-2026-09'),
    'inquiry_rate_limit' => (int) env('PZDIGITAL_INQUIRY_RATE_LIMIT', 8),
    'featured_project_slug' => 'gyroscity',
    'inquiry_interests' => [
        'website' => 'Új céges weboldal',
        'business_system' => 'Egyedi üzleti rendszer',
        'existing_system' => 'Meglévő rendszer továbbfejlesztése',
        'custom_development' => 'Más egyedi fejlesztés',
        'other' => 'Általános egyeztetés',
    ],

    'products' => [
        'szervizpro' => [
            'slug' => 'szervizpro',
            'name' => 'SzervizPRO',
            'eyebrow' => 'Szervizeknek tervezett rendszer',
            'headline' => 'Kevesebb adminisztráció. Átláthatóbb szervizmunka.',
            'summary' => 'Digitális munkalap, ügyfélkövetés és műhelykommunikáció egy átlátható rendszerben — kis- és közepes autószervizeknek.',
            'audience' => 'Kis- és közepes szervizek',
            'lifecycle_status' => 'pilot',
            'status_label' => 'Működő demó',
            'publication_status' => 'published',
            'content_approved' => true,
            'sort_order' => 10,
            'featured_on_home' => true,
            'demo_mode' => 'gallery',
            'demo_url' => null,
            'accent' => 'blue',
            'symbol' => '⌁',
            'visual_label' => 'Működő demó',
            'visual_title' => 'SzervizPRO · napi műhelyközpont',
            'primary_cta' => 'Bemutatót kérek',
            'benefits' => [
                'Digitális munkalapok és gyors státuszváltás.',
                'Ügyféloldali követés rendszám és azonosító alapján.',
                'Üzenetek, visszahívási kérések és publikus fotók egy helyen.',
            ],
            'flow' => [
                ['title' => 'Munkafelvétel', 'text' => 'Az ügyfél, a jármű, a hiba és a vállalt munka egy rendezett munkalapra kerül.'],
                ['title' => 'Műhelymunka', 'text' => 'A csapat a napi munkaközpontból követi az állapotokat, teendőket és ügyfélkéréseket.'],
                ['title' => 'Ügyféltájékoztatás', 'text' => 'Az ügyfél saját kóddal látja a státuszt, az üzeneteket, a várható elkészülést és a publikus fotókat.'],
            ],
            'screenshots' => [
                ['src' => '/media/pzdigital/szervizpro/dashboard.png', 'alt' => 'A SzervizPRO napi műhelyközpontja munkalap- és kommunikációs áttekintéssel', 'label' => 'Műhelynézet', 'title' => 'A napi teendők egy képernyőn'],
                ['src' => '/media/pzdigital/szervizpro/customer-home.png', 'alt' => 'A SzervizPRO ügyféloldali kezdőképernyője állapot-előnézettel', 'label' => 'Ügyféloldal', 'title' => 'Kevesebb telefon, érthetőbb tájékoztatás'],
                ['src' => '/media/pzdigital/szervizpro/status-lookup.png', 'alt' => 'Javítási állapot lekérdezése rendszám és kapott azonosító alapján', 'label' => 'Biztonságos lekérdezés', 'title' => 'Rendszám és azonosító alapján'],
            ],
            'related_projects' => [],
            'questions' => [
                ['question' => 'Mit láthatok a bemutatón?', 'answer' => 'A működő műhelynézetet, a digitális munkalapot és az ügyféloldali státuszkövetést mutatjuk meg, a saját folyamataidra koncentrálva.'],
                ['question' => 'Mennyi idő a bevezetés?', 'answer' => 'Az időigényt a szükséges beállítások és adat-előkészítés felmérése után lehet felelősen rögzíteni.'],
            ],
        ],
        'foodshop' => [
            'slug' => 'foodshop',
            'name' => 'FoodShop',
            'eyebrow' => 'Online rendelési megoldás',
            'headline' => 'Online rendelési megoldás, éles projekt tapasztalataira építve.',
            'summary' => 'A GyrosCity számára készült rendelési rendszer tapasztalataira épülő megoldás. A több vállalkozásnál bevezethető változat előkészítés alatt áll.',
            'audience' => 'Éttermek és vendéglátóhelyek',
            'lifecycle_status' => 'preview',
            'status_label' => 'Termékváltozat előkészítés alatt',
            'publication_status' => 'published',
            'content_approved' => true,
            'sort_order' => 20,
            'featured_on_home' => true,
            'demo_mode' => 'gallery',
            'demo_url' => null,
            'accent' => 'green',
            'symbol' => '✦',
            'visual_label' => 'Éles előzmény',
            'visual_title' => 'GyrosCity étlap — a FoodShop éles előzményének felülete',
            'primary_cta' => 'Érdeklődöm a megoldásról',
            'benefits' => [
                'Saját márkához illeszthető kínálati felület.',
                'Mobilon is áttekinthető étlap- és kategóriaszerkezet.',
                'A termékváltozat pontos keretei egyeztetés alatt állnak.',
            ],
            'flow' => [
                ['title' => 'Kínálat', 'text' => 'A termékek és kategóriák jól áttekinthető, mobilbarát bemutatása.'],
                ['title' => 'Rendelési út', 'text' => 'A kosár és a rendelés lépéseinek tervezett, egyszerű folyamata.'],
                ['title' => 'Feldolgozás', 'text' => 'A beérkező rendelések kezelőoldali feldolgozásának koncepciója.'],
            ],
            'screenshots' => [
                ['src' => '/media/pzdigital/references/gyroscity/menu-desktop.jpg', 'alt' => 'GyrosCity online étlap több valódi termékkártyával, nevekkel és árakkal', 'label' => 'Éles előzmény', 'title' => 'GyrosCity étlap — a FoodShop éles előzményének felülete'],
                ['src' => '/media/pzdigital/references/gyroscity/menu-mobile.jpg', 'alt' => 'GyrosCity mobilos étlapja a népszerű termékek listájával', 'label' => 'Mobilfelület', 'title' => 'Termékkínálat mobilon'],
            ],
            'related_projects' => [
                ['project_slug' => 'gyroscity', 'relationship' => 'origin'],
            ],
            'questions' => [
                ['question' => 'Elérhető már élő kipróbálás?', 'answer' => 'Nyilvános, írható demót csak elkülönített és biztonságosan ellenőrzött környezetben nyitunk meg. Jelenleg bemutató kérhető.'],
                ['question' => 'Van bankkártyás fizetés?', 'answer' => 'Az elérhető fizetési és külső integrációkat a konkrét projekt és szolgáltatói feltételek alapján egyeztetjük.'],
            ],
        ],
    ],

    'projects' => [
        'gyroscity' => [
            'slug' => 'gyroscity',
            'name' => 'GyrosCity',
            'showcase_headline' => 'GyrosCity — saját étlap és rendelési felület',
            'summary' => 'Éttermi weboldal és online rendelési felület kategóriákkal, kínálati kártyákkal és kosárfolyamattal.',
            'categories' => ['Éttermi weboldal', 'Online rendelés'],
            'project_type' => 'client_project',
            'delivery_context' => 'founder_prior_work',
            'role_description' => 'Korábbi fejlesztői munka a PZ Digital mögötti szakmai tapasztalatból.',
            'year' => null,
            'publication_status' => 'published',
            'content_approved' => true,
            'featured_on_home' => true,
            'sort_order' => 10,
            'public_url' => 'https://gyroscity.eu/',
            'accent' => 'amber',
            'media' => [
                ['src' => '/media/pzdigital/references/gyroscity/menu-desktop.jpg', 'card_src' => '/media/pzdigital/references/gyroscity/menu-card.jpg', 'alt' => 'GyrosCity online étlap több valódi termékkártyával, nevekkel és árakkal', 'viewport' => '1440 × 1000'],
                ['src' => '/media/pzdigital/references/gyroscity/menu-mobile.jpg', 'alt' => 'GyrosCity mobilos étlapja a népszerű termékek listájával', 'viewport' => '390 × 844'],
            ],
            'case_study_sections' => [
                'task' => 'Egy éttermi kínálat és a rendelési út áttekinthető megjelenítése asztali és mobilfelületen.',
                'role' => 'A publikus webes felület és a rendelési folyamat fejlesztése korábbi szakmai projektként.',
                'solutions' => ['Kategóriákba rendezett étlap', 'Termékkártyák és kosárfelület', 'Mobilra alkalmazkodó vásárlói nézet'],
            ],
            'source_reference' => 'https://pzoli.com/ és https://gyroscity.eu/',
        ],
        'zcutzbarber' => [
            'slug' => 'zcutzbarber',
            'name' => 'ZCutzBarber',
            'summary' => 'Márkázott szolgáltatói weboldal bemutatkozással, szolgáltatásokkal, árlistával és időpontfoglalási felülettel.',
            'categories' => ['Szolgáltatói weboldal', 'Időpontfoglalás'],
            'project_type' => 'client_project',
            'delivery_context' => 'founder_prior_work',
            'role_description' => 'Korábbi fejlesztői munka a PZ Digital mögötti szakmai tapasztalatból.',
            'year' => null,
            'publication_status' => 'published',
            'content_approved' => true,
            'featured_on_home' => true,
            'sort_order' => 20,
            'public_url' => 'https://zcutzbarber.com/',
            'accent' => 'lime',
            'media' => [
                ['src' => '/media/pzdigital/references/zcutzbarber/desktop.jpg', 'alt' => 'ZCutzBarber szolgáltatói weboldal — asztali képernyőkép', 'viewport' => '1440 × 1000'],
                ['src' => '/media/pzdigital/references/zcutzbarber/mobile.jpg', 'alt' => 'ZCutzBarber mobilos bemutatkozó felület — képernyőkép', 'viewport' => '390 × 844'],
            ],
            'case_study_sections' => [
                'task' => 'A barber márka, a szolgáltatások és a kapcsolatfelvételi lehetőségek egységes online bemutatása.',
                'role' => 'A publikus márkaoldal és a látogatói út fejlesztése korábbi szakmai projektként.',
                'solutions' => ['Márkázott bemutatkozó felület', 'Szolgáltatás- és árlista', 'Látható időpontfoglalási lehetőség'],
            ],
            'source_reference' => 'https://pzoli.com/ és https://zcutzbarber.com/',
        ],
        'tiszaszalka-se' => [
            'slug' => 'tiszaszalka-se',
            'name' => 'Tiszaszalka SE',
            'summary' => 'Sportegyesületi weboldal hírekkel, mérkőzésadatokkal, tabellával, dokumentumokkal és galériával.',
            'categories' => ['Egyesületi weboldal', 'Sporttartalom'],
            'project_type' => 'client_project',
            'delivery_context' => 'founder_prior_work',
            'role_description' => 'Korábbi fejlesztői munka a PZ Digital mögötti szakmai tapasztalatból.',
            'year' => null,
            'publication_status' => 'published',
            'content_approved' => true,
            'featured_on_home' => false,
            'sort_order' => 30,
            'public_url' => 'https://tiszaszalkase.com/',
            'accent' => 'forest',
            'media' => [
                ['src' => '/media/pzdigital/references/tiszaszalka-se/desktop.jpg', 'alt' => 'Tiszaszalka SE sportegyesületi weboldal — asztali képernyőkép', 'viewport' => '1440 × 1000'],
                ['src' => '/media/pzdigital/references/tiszaszalka-se/mobile.jpg', 'alt' => 'Tiszaszalka SE mobilos weboldal — képernyőkép', 'viewport' => '390 × 844'],
            ],
            'case_study_sections' => [
                'task' => 'Az egyesületi hírek és a nyilvános sportinformációk rendezett, közös felületen történő bemutatása.',
                'role' => 'A publikus információs oldal fejlesztése korábbi szakmai projektként.',
                'solutions' => ['Hírek és mérkőzéslista', 'Tabella és szezoninformációk', 'Dokumentumok és képgaléria'],
            ],
            'source_reference' => 'https://pzoli.com/ és https://tiszaszalkase.com/',
        ],
        'napiinfo' => [
            'slug' => 'napiinfo',
            'name' => 'NapiInfo',
            'summary' => 'Tartalmi portál kiemelt cikkekkel, témakörökkel, friss hírekkel és többféle olvasási belépési ponttal.',
            'categories' => ['Tartalmi portál', 'Szerkesztett cikkek'],
            'project_type' => 'unspecified',
            'delivery_context' => 'founder_prior_work',
            'role_description' => 'Korábbi fejlesztői munka a PZ Digital mögötti szakmai tapasztalatból.',
            'year' => null,
            'publication_status' => 'published',
            'content_approved' => true,
            'featured_on_home' => true,
            'sort_order' => 40,
            'public_url' => 'https://napiinfo.com/',
            'accent' => 'red',
            'media' => [
                ['src' => '/media/pzdigital/references/napiinfo/desktop.jpg', 'alt' => 'NapiInfo tartalmi portál — asztali képernyőkép', 'viewport' => '1440 × 1000'],
                ['src' => '/media/pzdigital/references/napiinfo/mobile.jpg', 'alt' => 'NapiInfo mobilos cikkfelület — képernyőkép', 'viewport' => '390 × 844'],
            ],
            'case_study_sections' => [
                'task' => 'Sokféle témájú cikk áttekinthető szervezése és több belépési pont biztosítása az olvasóknak.',
                'role' => 'A publikus tartalmi felület fejlesztése korábbi szakmai projektként.',
                'solutions' => ['Kiemelt és friss cikkek', 'Témakörök és kategóriaoldalak', 'Reszponzív tartalmi kártyarendszer'],
            ],
            'source_reference' => 'https://pzoli.com/ és https://napiinfo.com/',
        ],
    ],
];
