<?php

return [
    'brand' => [
        'name' => 'SzoftPont',
        'tagline' => 'SzoftPont. Pont arra, amire szükséged van.',
        // Set only after the new mailbox has been provisioned and approved.
        'contact_email' => env('SZOFTPONT_CONTACT_EMAIL'),
    ],
    'contact_email' => env('PZDIGITAL_CONTACT_EMAIL', 'hello@pzdigital.hu'),
    'privacy_version' => env('PZDIGITAL_PRIVACY_VERSION', 'draft-2026-09'),
    'inquiry_rate_limit' => (int) env('PZDIGITAL_INQUIRY_RATE_LIMIT', 8),
    'featured_project_slug' => 'gyroscity',
    'homepage_story_project_slugs' => ['napiinfo', 'gyroscity', 'zcutzbarber'],
    'home' => [
        'show_references' => (bool) env('PZDIGITAL_HOME_SHOW_REFERENCES', true),
        'enable_product_design_preview' => (bool) env('PZDIGITAL_HOME_ENABLE_PRODUCT_DESIGN_PREVIEW', false),
        'product_placeholder' => [
            'name' => 'Következő saját termék',
            'summary' => 'A részletes bemutató előkészítés alatt.',
        ],
    ],
    'inquiry_interests' => [
        'website' => 'Új céges weboldal',
        'business_system' => 'Egyedi üzleti rendszer',
        'existing_system' => 'Meglévő rendszer továbbfejlesztése',
        'custom_development' => 'Más egyedi fejlesztés',
        'other' => 'Általános egyeztetés',
    ],

    'products' => [
        'szervizpro' => [
            'slug' => 'szervizpro',
            'name' => 'SzervizPRO',
            'eyebrow' => 'Szervizeknek tervezett rendszer',
            'headline' => 'Kevesebb adminisztráció. Átláthatóbb szervizmunka.',
            'summary' => 'Digitális munkalap, ügyfélkövetés és műhelykommunikáció egy átlátható rendszerben — kis- és közepes autószervizeknek.',
            'audience' => 'Kis- és közepes szervizek',
            'lifecycle_status' => 'pilot',
            'status_label' => 'Bemutató elérhető',
            'publication_status' => 'published',
            'content_approved' => true,
            'sort_order' => 10,
            'featured_on_home' => true,
            'demo_mode' => 'gallery',
            'demo_url' => null,
            'accent' => 'blue',
            'symbol' => '⌁',
            'visual_label' => 'Bemutató elérhető',
            'visual_title' => 'SzervizPRO · napi műhelyközpont',
            'primary_cta' => 'Bemutatót kérek',
            'benefits' => [
                'Digitális munkalapok és gyors státuszváltás.',
                'Ügyféloldali követés rendszám és azonosító alapján.',
                'Üzenetek, visszahívási kérések és publikus fotók egy helyen.',
            ],
            'flow' => [
                ['title' => 'Munkafelvétel', 'text' => 'Az ügyfél, a jármű, a hiba és a vállalt munka egy rendezett munkalapra kerül.'],
                ['title' => 'Műhelymunka', 'text' => 'A csapat a napi munkaközpontból követi az állapotokat, teendőket és ügyfélkéréseket.'],
                ['title' => 'Ügyféltájékoztatás', 'text' => 'Az ügyfél saját kóddal látja a státuszt, az üzeneteket, a várható elkészülést és a publikus fotókat.'],
            ],
            'home_flow' => [
                ['title' => 'Munkafelvétel', 'icon' => 'flow'],
                ['title' => 'Programozás', 'icon' => 'code'],
                ['title' => 'Egyeztetés', 'icon' => 'people'],
                ['title' => 'Átadás', 'icon' => 'shield'],
            ],
            'screenshots' => [
                ['src' => '/media/pzdigital/szervizpro/dashboard.png', 'alt' => 'A SzervizPRO napi műhelyközpontja munkalap- és kommunikációs áttekintéssel', 'label' => 'Műhelynézet', 'title' => 'A napi teendők egy képernyőn'],
                ['src' => '/media/pzdigital/szervizpro/customer-home.png', 'alt' => 'A SzervizPRO ügyféloldali kezdőképernyője állapot-előnézettel', 'label' => 'Ügyféloldal', 'title' => 'Kevesebb telefon, érthetőbb tájékoztatás'],
                ['src' => '/media/pzdigital/szervizpro/status-lookup.png', 'alt' => 'Javítási állapot lekérdezése rendszám és kapott azonosító alapján', 'label' => 'Biztonságos lekérdezés', 'title' => 'Rendszám és azonosító alapján'],
            ],
            'demo_highlights' => [
                ['title' => 'Egy munkalap, a felvételtől az átadásig', 'text' => 'A bemutatón végignézzük a munkafelvételt és az állapotok követését. Így a saját műhelyed egy tipikus feladatán keresztül ismerheted meg a rendszert.', 'image' => null],
                ['title' => 'Az ügyfél is látja, hol tart a javítás', 'text' => 'Megmutatjuk az azonosítós státuszkövetést, az üzeneteket és a megosztható fotókat. Átbeszéljük, mely információkat szeretnéd láthatóvá tenni.', 'image' => null],
            ],
            'related_projects' => [],
            'questions' => [
                ['question' => 'Mit láthatok a bemutatón?', 'answer' => 'A működő műhelynézetet, a digitális munkalapot és az ügyféloldali státuszkövetést mutatjuk meg, a saját folyamataidra koncentrálva.'],
                ['question' => 'Mennyi idő a bevezetés?', 'answer' => 'Az időigényt a szükséges beállítások és adat-előkészítés felmérése után lehet felelősen rögzíteni.'],
            ],
        ],
        'foodshop' => [
            'slug' => 'foodshop',
            'name' => 'FoodShop',
            'eyebrow' => 'Online rendelési megoldás',
            'headline' => 'Online rendelési megoldás, éles projekt tapasztalataira építve.',
            'summary' => 'A GyrosCity rendelési rendszerére épülő megoldás. A több vállalkozásnál bevezethető változat előkészítés alatt áll.',
            'audience' => 'Éttermek és vendéglátóhelyek',
            'lifecycle_status' => 'preview',
            'status_label' => 'Előkészítés alatt',
            'publication_status' => 'published',
            'content_approved' => true,
            'sort_order' => 20,
            'featured_on_home' => true,
            'demo_mode' => 'gallery',
            'demo_url' => null,
            'accent' => 'green',
            'symbol' => '✦',
            'visual_label' => 'A FoodShop alapja: GyrosCity',
            'visual_title' => 'GyrosCity étlap — a FoodShop alapja',
            'primary_cta' => 'Érdeklődöm a megoldásról',
            'benefits' => [
                'Saját márkához illeszthető kínálati felület.',
                'Mobilon is áttekinthető étlap- és kategóriaszerkezet.',
                'A termékváltozat pontos keretei egyeztetés alatt állnak.',
            ],
            'flow' => [
                ['title' => 'Kínálat', 'text' => 'A termékek és kategóriák jól áttekinthető, mobilbarát bemutatása.'],
                ['title' => 'Rendelési út', 'text' => 'A kosár és a rendelés lépéseinek tervezett, egyszerű folyamata.'],
                ['title' => 'Feldolgozás', 'text' => 'A beérkező rendelések kezelőoldali feldolgozásának koncepciója.'],
            ],
            'screenshots' => [
                ['src' => '/media/pzdigital/references/gyroscity/menu-desktop.jpg', 'alt' => 'GyrosCity online étlap több valódi termékkártyával, nevekkel és árakkal', 'label' => 'Éles előzmény', 'title' => 'GyrosCity étlap — a FoodShop éles előzményének felülete'],
                ['src' => '/media/pzdigital/references/gyroscity/menu-mobile.jpg', 'alt' => 'GyrosCity mobilos étlapja a népszerű termékek listájával', 'label' => 'Mobilfelület', 'title' => 'Termékkínálat mobilon', 'orientation' => 'portrait', 'width' => 390, 'height' => 844],
            ],
            'demo_highlights' => [
                ['title' => 'A kínálattól a rendelésig', 'text' => 'A GyrosCity éles előzménye alapján bemutatjuk a vendégoldali rendelési utat. A FoodShop termékváltozatának pontos funkcióit egyeztetjük.', 'image' => null],
                ['title' => 'Mi történik a rendelés beérkezése után?', 'text' => 'Átbeszéljük a kezelőoldali feldolgozást és az éttermed igényeit. A termékváltozat előkészítés alatt áll; nyilvános tesztrendelés jelenleg nem érhető el.', 'image' => null],
            ],
            'related_projects' => [
                ['project_slug' => 'gyroscity', 'relationship' => 'origin'],
            ],
            'questions' => [
                ['question' => 'Elérhető már élő kipróbálás?', 'answer' => 'Nyilvános, írható demót csak elkülönített és biztonságosan ellenőrzött környezetben nyitunk meg. Jelenleg bemutató kérhető.'],
                ['question' => 'Van bankkártyás fizetés?', 'answer' => 'Az elérhető fizetési és külső integrációkat a konkrét projekt és szolgáltatói feltételek alapján egyeztetjük.'],
            ],
        ],
    ],

    'projects' => [
        'gyroscity' => [
            'slug' => 'gyroscity',
            'name' => 'GyrosCity',
            'showcase_headline' => 'GyrosCity — saját étlap és rendelési felület',
            'showcase_label' => 'Rendelés',
            'showcase_title' => 'Rendelési felület és kezelőoldali feldolgozás',
            'showcase_flow' => 'Étlap → rendelés → adminisztrátori kezelés',
            'home_feature' => 'Online rendelés és rendeléskezelő admin',
            'summary' => 'Éttermi weboldal és online rendelési felület kategóriákkal, kínálati kártyákkal és kosárfolyamattal.',
            'categories' => ['Éttermi weboldal', 'Online rendelés'],
            'project_type' => 'client_project',
            'delivery_context' => 'founder_prior_work',
            'role_description' => 'Korábbi fejlesztői munka a SzoftPont mögötti szakmai tapasztalatból.',
            'year' => null,
            'publication_status' => 'published',
            'content_approved' => true,
            'featured_on_home' => true,
            'sort_order' => 10,
            'public_url' => 'https://gyroscity.eu/',
            'accent' => 'amber',
            'media' => [
                ['src' => '/media/pzdigital/references/gyroscity/menu-desktop.jpg', 'card_src' => '/media/pzdigital/references/gyroscity/menu-card.jpg', 'alt' => 'GyrosCity online étlap több valódi termékkártyával, nevekkel és árakkal', 'viewport' => '1440 × 1000'],
                ['src' => '/media/pzdigital/references/gyroscity/menu-mobile.jpg', 'alt' => 'GyrosCity mobilos étlapja a népszerű termékek listájával', 'viewport' => '390 × 844'],
            ],
            'case_study_sections' => [
                'task' => 'Egy éttermi kínálat és a rendelési út áttekinthető megjelenítése asztali és mobilfelületen.',
                'role' => 'A publikus webes felület és a rendelési folyamat fejlesztése korábbi szakmai projektként.',
                'solutions' => ['Kategóriákba rendezett étlap', 'Termékkártyák és kosárfelület', 'Mobilra alkalmazkodó vásárlói nézet'],
            ],
            'case_study' => [
                'headline' => 'GyrosCity — étlap és rendeléskezelés egy rendszerben.',
                'lead' => 'Az éttermi kínálat böngészésétől a rendelés kezelőoldali feldolgozásáig egy összefüggő webes folyamat készült.',
                'audience' => 'Éttermi vendégek és a rendeléseket kezelő csapat',
                'blocks' => [
                    ['type' => 'overview', 'heading' => 'A vendégoldal és a háttérfolyamat', 'public_side' => 'A vendég kategóriák szerint böngészi a kínálatot, terméket választ, majd a rendelési úton halad tovább.', 'admin_side' => 'A beérkező rendelések az adminfelületen kezelhetők.', 'publication_status' => 'published', 'evidence_status' => 'owner_confirmed'],
                    ['type' => 'workflow', 'heading' => 'Hogyan működik?', 'steps' => [
                        ['title' => 'Étlap', 'body' => 'A valós terméklistán kategóriák, terméknevek és árak jelennek meg.'],
                        ['title' => 'Rendelés', 'body' => 'A kiválasztott tételek a vendégoldali rendelési folyamatba kerülnek.'],
                        ['title' => 'Feldolgozás', 'body' => 'A rendelést a kezelőoldali adminisztrációban lehet feldolgozni.'],
                    ], 'publication_status' => 'published', 'evidence_status' => 'owner_confirmed'],
                    ['type' => 'integration', 'heading' => 'Éles előzmény a FoodShop mögött', 'body' => 'Az itt bemutatott rendszer a FoodShop előkészítés alatt álló termékváltozatának éles előzménye. Ez nem jelent kész, több vállalkozásnál azonnal bevezethető terméket.', 'publication_status' => 'published', 'evidence_status' => 'owner_confirmed'],
                    ['type' => 'gallery', 'heading' => 'A valódi étlapfelület', 'body' => 'Nyilvános asztali és mobilképek; a háttérfolyamatot külön, jelölt szemléltető magyarázza.', 'publication_status' => 'published', 'evidence_status' => 'public_screen'],
                    ['type' => 'outcome', 'heading' => 'Amit megvalósítottunk', 'items' => ['Kategóriákba rendezett, reszponzív étlap', 'Vendégoldali rendelési út', 'Rendeléskezelő adminisztráció'], 'publication_status' => 'published', 'evidence_status' => 'owner_confirmed'],
                ],
                'missing_assets' => ['Jóváhagyott, szintetikus adatú admin-képernyő'],
            ],
            'source_reference' => 'https://pzoli.com/ és https://gyroscity.eu/',
        ],
        'zcutzbarber' => [
            'slug' => 'zcutzbarber',
            'name' => 'ZCutzBarber',
            'showcase_label' => 'Foglalás',
            'showcase_title' => 'Online időpontfoglalás naptárkapcsolattal',
            'showcase_flow' => 'Időpontválasztás → foglalás → Google Naptár-kapcsolat',
            'home_feature' => 'Időpontfoglalás Google Naptár-kapcsolattal',
            'summary' => 'Márkázott szolgáltatói weboldal bemutatkozással, szolgáltatásokkal, árlistával és időpontfoglalási felülettel.',
            'categories' => ['Szolgáltatói weboldal', 'Időpontfoglalás'],
            'project_type' => 'client_project',
            'delivery_context' => 'founder_prior_work',
            'role_description' => 'Korábbi fejlesztői munka a SzoftPont mögötti szakmai tapasztalatból.',
            'year' => null,
            'publication_status' => 'published',
            'content_approved' => true,
            'featured_on_home' => true,
            'sort_order' => 20,
            'public_url' => 'https://zcutzbarber.com/',
            'accent' => 'lime',
            'media' => [
                ['src' => '/media/pzdigital/references/zcutzbarber/desktop.jpg', 'alt' => 'ZCutzBarber szolgáltatói weboldal — asztali képernyőkép', 'viewport' => '1440 × 1000'],
                ['src' => '/media/pzdigital/references/zcutzbarber/mobile.jpg', 'alt' => 'ZCutzBarber mobilos bemutatkozó felület — képernyőkép', 'viewport' => '390 × 844'],
            ],
            'case_study_sections' => [
                'task' => 'A barber márka, a szolgáltatások és a kapcsolatfelvételi lehetőségek egységes online bemutatása.',
                'role' => 'A publikus márkaoldal és a látogatói út fejlesztése korábbi szakmai projektként.',
                'solutions' => ['Márkázott bemutatkozó felület', 'Szolgáltatás- és árlista', 'Látható időpontfoglalási lehetőség'],
            ],
            'case_study' => [
                'headline' => 'ZCutzBarber — online foglalás, naptárkapcsolattal.',
                'lead' => 'A márkaoldal az időpontfoglalási utat Google Naptár-kapcsolattal egészíti ki.',
                'audience' => 'Vendégek és a foglalásokat kezelő szolgáltató',
                'blocks' => [
                    ['type' => 'overview', 'heading' => 'Szolgáltatási oldal és foglalási háttér', 'public_side' => 'A látogató megismeri a szolgáltatásokat és az árakat, majd eléri az online időpontfoglalást.', 'admin_side' => 'A foglalás kezelése Google Naptár-kapcsolathoz illeszkedik. A szinkron irányáról, idejéről vagy ütközéskezeléséről nincs publikált állítás.', 'publication_status' => 'published', 'evidence_status' => 'owner_confirmed'],
                    ['type' => 'workflow', 'heading' => 'Hogyan működik?', 'steps' => [
                        ['title' => 'Időpontválasztás', 'body' => 'A vendég a foglalási felületen választ megfelelő időpontot.'],
                        ['title' => 'Foglalás kezelése', 'body' => 'A kiválasztás kezelhető foglalássá válik a szolgáltatói folyamatban.'],
                        ['title' => 'Naptárkapcsolat', 'body' => 'A rendszer kapcsolódik a Google Naptárhoz; a szemléltetés nem hoz létre valódi eseményt.'],
                    ], 'publication_status' => 'published', 'evidence_status' => 'owner_confirmed'],
                    ['type' => 'integration', 'heading' => 'Google Naptár-kapcsolat, pontos határokkal', 'body' => 'A naptárkapcsolat megerősített funkció. Kétirányú szinkront, automatikus emlékeztetőt, fizetést vagy garantált ütközésmentességet nem állítunk.', 'publication_status' => 'published', 'evidence_status' => 'owner_confirmed'],
                    ['type' => 'gallery', 'heading' => 'Márka- és foglalási felület', 'body' => 'A nyilvános képek a szolgáltatói weboldalt mutatják; naptárképernyő csak jóváhagyott tesztadatból kerülhet ki később.', 'publication_status' => 'published', 'evidence_status' => 'public_screen'],
                    ['type' => 'outcome', 'heading' => 'Igazoltan elkészült', 'items' => ['Márkázott szolgáltatói weboldal', 'Online időpontfoglalás', 'Google Naptár-kapcsolat'], 'publication_status' => 'published', 'evidence_status' => 'owner_confirmed'],
                ],
                'missing_assets' => ['Jóváhagyott, tesztadatú naptárképernyő'],
            ],
            'source_reference' => 'https://pzoli.com/ és https://zcutzbarber.com/',
        ],
        'tiszaszalka-se' => [
            'slug' => 'tiszaszalka-se',
            'name' => 'Tiszaszalka SE',
            'showcase_label' => 'Adatszinkron',
            'showcase_title' => 'Sporteredmények automatikus átvétele',
            'showcase_flow' => 'MLSZ Adatbank → automatikus átvétel → kluboldal',
            'summary' => 'Sportegyesületi weboldal hírekkel, mérkőzésadatokkal, tabellával, dokumentumokkal és galériával.',
            'categories' => ['Egyesületi weboldal', 'Sporttartalom'],
            'project_type' => 'client_project',
            'delivery_context' => 'founder_prior_work',
            'role_description' => 'Korábbi fejlesztői munka a SzoftPont mögötti szakmai tapasztalatból.',
            'year' => null,
            'publication_status' => 'published',
            'content_approved' => true,
            'featured_on_home' => false,
            'sort_order' => 30,
            'public_url' => 'https://tiszaszalkase.com/',
            'accent' => 'forest',
            'media' => [
                ['src' => '/media/pzdigital/references/tiszaszalka-se/desktop.jpg', 'alt' => 'Tiszaszalka SE sportegyesületi weboldal — asztali képernyőkép', 'viewport' => '1440 × 1000'],
                ['src' => '/media/pzdigital/references/tiszaszalka-se/mobile.jpg', 'alt' => 'Tiszaszalka SE mobilos weboldal — képernyőkép', 'viewport' => '390 × 844'],
            ],
            'case_study_sections' => [
                'task' => 'Az egyesületi hírek és a nyilvános sportinformációk rendezett, közös felületen történő bemutatása.',
                'role' => 'A publikus információs oldal fejlesztése korábbi szakmai projektként.',
                'solutions' => ['Hírek és mérkőzéslista', 'Tabella és szezoninformációk', 'Dokumentumok és képgaléria'],
            ],
            'case_study' => [
                'headline' => 'Tiszaszalka SE — eredmények, kézi másolgatás nélkül.',
                'lead' => 'A sportoldal az MLSZ Adatbankból automatikusan átvett eredményeket rendezi a klub saját felületére.',
                'audience' => 'Szurkolók, játékosok és az egyesületi tartalmak kezelői',
                'blocks' => [
                    ['type' => 'overview', 'heading' => 'Kluboldal és adatforrás', 'public_side' => 'A látogató híreket, mérkőzésadatokat, eredményeket és a klub további nyilvános tartalmait éri el.', 'admin_side' => 'Az eredmények forrása az MLSZ Adatbank, ahonnan automatikus átvétel történik. A bemutató nem állít valós idejű vagy kétirányú kapcsolatot.', 'publication_status' => 'published', 'evidence_status' => 'owner_confirmed'],
                    ['type' => 'workflow', 'heading' => 'Hogyan működik?', 'steps' => [
                        ['title' => 'Forrásadat', 'body' => 'A mérkőzés eredménye az MLSZ Adatbank nyilvános sportadatából indul.'],
                        ['title' => 'Automatikus átvétel', 'body' => 'A rendszer a szükséges eredményadatot automatikusan átveszi.'],
                        ['title' => 'Kluboldali megjelenés', 'body' => 'Az adat a Tiszaszalka SE saját eredményfelületén jelenik meg.'],
                    ], 'publication_status' => 'published', 'evidence_status' => 'owner_confirmed'],
                    ['type' => 'integration', 'heading' => 'MLSZ Adatbank, nem banki adatforrás', 'body' => 'A forrás megnevezése MLSZ Adatbank. Nincs állítás hivatalos API-partnerségről, élő frissítési garanciáról vagy kétirányú adatszinkronról.', 'publication_status' => 'published', 'evidence_status' => 'owner_confirmed'],
                    ['type' => 'gallery', 'heading' => 'A klub nyilvános felülete', 'body' => 'A képek az egyesület asztali és mobiloldalát mutatják; a forrástól a felületig tartó út jelölt szemléltetés.', 'publication_status' => 'published', 'evidence_status' => 'public_screen'],
                    ['type' => 'outcome', 'heading' => 'Igazoltan elkészült', 'items' => ['Egyesületi hírek és mérkőzésadatok', 'Automatikus eredményátvétel az MLSZ Adatbankból', 'Reszponzív kluboldali megjelenés'], 'publication_status' => 'published', 'evidence_status' => 'owner_confirmed'],
                ],
                'missing_assets' => ['Publikálható forrásimport-napló vagy admin-képernyő'],
            ],
            'source_reference' => 'https://pzoli.com/ és https://tiszaszalkase.com/',
        ],
        'napiinfo' => [
            'slug' => 'napiinfo',
            'name' => 'NapiInfo',
            'showcase_label' => 'AI-tartalom',
            'showcase_title' => 'Tulajdonosi utasításból szerkeszthető cikk',
            'showcase_flow' => 'Utasítás → AI-cikktervezet → szerkesztési folyamat',
            'home_feature' => 'AI-val támogatott cikkgyártás',
            'summary' => 'Tartalmi portál kiemelt cikkekkel, témakörökkel, friss hírekkel és többféle olvasási belépési ponttal.',
            'categories' => ['Tartalmi portál', 'Szerkesztett cikkek'],
            'project_type' => 'unspecified',
            'delivery_context' => 'founder_prior_work',
            'role_description' => 'Korábbi fejlesztői munka a SzoftPont mögötti szakmai tapasztalatból.',
            'year' => null,
            'publication_status' => 'published',
            'content_approved' => true,
            'featured_on_home' => true,
            'sort_order' => 40,
            'public_url' => 'https://napiinfo.com/',
            'accent' => 'red',
            'media' => [
                ['src' => '/media/pzdigital/references/napiinfo/desktop.jpg', 'alt' => 'NapiInfo tartalmi portál — asztali képernyőkép', 'viewport' => '1440 × 1000'],
                ['src' => '/media/pzdigital/references/napiinfo/mobile.jpg', 'alt' => 'NapiInfo mobilos cikkfelület — képernyőkép', 'viewport' => '390 × 844'],
            ],
            'case_study_sections' => [
                'task' => 'Sokféle témájú cikk áttekinthető szervezése és több belépési pont biztosítása az olvasóknak.',
                'role' => 'A publikus tartalmi felület fejlesztése korábbi szakmai projektként.',
                'solutions' => ['Kiemelt és friss cikkek', 'Témakörök és kategóriaoldalak', 'Reszponzív tartalmi kártyarendszer'],
            ],
            'case_study' => [
                'headline' => 'NapiInfo — az utasítástól a cikkig.',
                'lead' => 'AI-val támogatott tartalom-előállítás, amely a tulajdonosi iránymutatást kapcsolja össze a weboldal szerkesztési folyamatával.',
                'audience' => 'A portál tulajdonosa, szerkesztői és olvasói',
                'blocks' => [
                    ['type' => 'overview', 'heading' => 'Olvasói felület és tartalom-előállítás', 'public_side' => 'Az olvasó témakörök, kiemelt és friss cikkek között böngészhet a reszponzív portálon.', 'admin_side' => 'A tulajdonosi utasításból AI-cikktervezet indul, amely szerkesztési folyamatba kerül. A bemutató nem állít felügyelet nélküli automatikus publikálást.', 'publication_status' => 'published', 'evidence_status' => 'owner_confirmed'],
                    ['type' => 'workflow', 'heading' => 'Hogyan működik?', 'steps' => [
                        ['title' => 'Tulajdonosi utasítás', 'body' => 'A folyamat egy előre megadott témából és iránymutatásból indul.'],
                        ['title' => 'AI-cikktervezet', 'body' => 'A rendszer szerkeszthető cikktervezetet állít össze; ez nem élő AI-futtatás ezen az oldalon.'],
                        ['title' => 'Szerkesztési folyamat', 'body' => 'A tervezet a weboldal tartalomkezelési folyamatába kerül. A publikálás mai pontos rendje külön ellenőrzendő.'],
                    ], 'publication_status' => 'published', 'evidence_status' => 'owner_confirmed_with_historical_boundary'],
                    ['type' => 'integration', 'heading' => 'AI-támogatás, emberi iránymutatással', 'body' => 'A szemléltető helyi, rögzített mintával dolgozik. Nem hív AI-szolgáltatót, nem tartalmaz belső promptot, és nem ígér automatikus tényellenőrzést vagy hibamentességet.', 'publication_status' => 'published', 'evidence_status' => 'owner_confirmed'],
                    ['type' => 'gallery', 'heading' => 'A tényleges portálfelület', 'body' => 'A képek a nyilvános olvasói oldalt mutatják; jóváhagyott, anonimizált szerkesztői kép még nem áll rendelkezésre.', 'publication_status' => 'published', 'evidence_status' => 'public_screen'],
                    ['type' => 'outcome', 'heading' => 'Igazoltan elkészült', 'items' => ['Tulajdonosi iránymutatásból induló AI-cikktervezet', 'Szerkesztési folyamatba kapcsolt tartalom-előállítás', 'Reszponzív, témakörökre rendezett cikkportál'], 'publication_status' => 'published', 'evidence_status' => 'owner_confirmed'],
                ],
                'missing_assets' => ['Jóváhagyott, anonimizált szerkesztői képernyő', 'A jelenlegi publikálási sorrend friss auditja'],
            ],
            'source_reference' => 'https://pzoli.com/ és https://napiinfo.com/',
        ],
    ],
];
